# Trigger of the pipeline
on:
  push:
    branches:
      - kisan  # Trigger on the 'kisan' branch

jobs:
  # Stage 1: Building the Docker image
  build-docker-image:
    name: Build the application Docker image
    runs-on: csd-windows-local  # Using the self-hosted Windows runner
    steps:
      - name: Clone and Checkout to the repository
        uses: actions/checkout@v2  # GitHub action to clone the repository

      - name: Build Docker Image
        run: docker build -t student-record-management:v1.0.1 -f Dockerfile .

  # Stage 2: Deploying the Docker image
  deploy-docker-image:
    name: Deploy the Flask image
    runs-on: csd-windows-local  # Using the self-hosted Windows runner
    steps:
      - name: Deploy the image
        run: docker run -d -p 5000:5000 student-record-management:v1.0.1  # Run container in the background

  # Stage 3: Running unit tests
  unit-test:
    name: Run unit tests for the application
    runs-on: ubuntu-latest  # Using a Linux runner for testing
    needs: [build-docker-image]  # Ensure this runs after Docker image build
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Adjust Python version if necessary

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          pytest  # Or any other test command you use (e.g., pytest, unittest)
