#Trigger of the pipeline
on:
  #initiates the pipeline when there is  push event in the main branch
  push:
    branches:
      - Kisan-Tset

jobs:
  #Stage 1: Building the docker image
  build-docker-image:
    #description of the job
    name: The job to build the application docker image
    #To define the machine  that  runs a job we use "runs-on"
    runs-on: csd-windows-local #Using the self-hosted runner
    #The instructions are defined as steps
    steps:
      - name: Clone and Checkout to the repository
        uses: actions/checkout@v2 # this is a GitHub action (pre-defined job)
                                  # that clones the project into the working directory.

      - name: Build Docker Image
        run: docker build -t student-record-management:v1.0.1 -f Dockerfile .

  deploy-docker-image:
    name: Deploy the flask image
    runs-on: csd-windows-local # Using the self-hosted runner
    steps:
      - name: Deploy the image
        run: docker run -d -p 5000:5000 student-record-management:v1.0.1 # -d tag allows the container in the background.Reuning busey port agian

    #Stage 3: Running test cases
    test:
      name: Unit testing of the application
      needs: [build-docker-image]
      runs-on: csd-windows-local
      steps:
        - name: Clone and Checkout to the repository
          uses: actions/checkout@v2

        - name: Set up a virtual environment
          run: |
            python -m venv venv 
            venv/Scripts/activate
            pip install -r requirements.txt

        - name: Run unit tests inside the virtual environment
          run: |
            venv/Scripts/activate
            pytest tests/